name: Update README table of contents

on:
  push:
    branches: [ main, master ]
    paths:
      - README.md
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Update TOC in README.md
        run: npx markdown-toc -i README.md
      - name: Commit and push if README changed
        run: |
          git diff
          git config --global user.email "toc-bot@davidcraddock.net"
          git config --global user.name "toc-bot"
          git diff --quiet || (git add README.md && git commit -m "Updated README TOC")
          git push

